### ISSUE TITLE
funq plot: how to make the bin size clearer

### ISSUE THREAD

**Issue by mtennekes** [edwindj/qbinplots#3]
I really like the funq plot. One thing that could be improved: it may not always be clear how large the bin sizes are (depends on the data).

Is there a way to improve this? Ideas:

* tiny vertical separation lines between the bins.
* compute it for several bin sizes and add a slider for those

**Comment by edwindj** [comment]
Thanks, I like them also a lot!

- thanks for the suggestions: we should do some experiments with that :-)
- it is currently possible to add a rug (`add_rug=TRUE`) that shows the bin boundaries on the x-axis. The argument should be renamed (`add_bin_boundaries`?), and open for suggestions for improvement.
